language: ruby
rvm:
  - 2.2.0
addons:
  postgresql: "9.4"
before_install:
  - gem install rake
  - gem install bundler -v 1.16.2
before_script:
  - psql -c 'create database tutsplus_ci_test' -U postgres
  - cp config/database.yml.travis config/database.yml
