language: ruby
rvm:
  - 2.7.0
addons:
  postgresql: "12.2"
before_script:
  - gem install bundler:1.17.2
  - psql -c 'create database tutsplus_ci_test' -U postgres
  - cp config/database.yml.travis config/database.yml
